//! `pdm.lock` graph extraction.

use std::collections::BTreeMap;
use std::path::Path;

use toml::Value;

use super::error::ManifestError;
use super::lockfile::{array_tables, merge_package, read_lock_table};
use super::pep508_util::normalize_distribution_name;
use super::types::LockfileGraph;

/// Parse `pdm.lock` (pdm 2.x) into a dependency name graph.
///
/// `groups` / `extras` are dropped: declaration contexts come from the
/// manifest, and the graph only answers "reachable from a declared dependency".
pub fn extract_pdm_lock(path: &Path) -> Result<LockfileGraph, ManifestError> {
    let table = read_lock_table(path)?;
    let mut edges = BTreeMap::new();
    for package in array_tables(&table, "package") {
        let Some(name) = package.get("name").and_then(Value::as_str) else {
            continue;
        };
        let deps = package
            .get("dependencies")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .filter_map(Value::as_str)
            .filter_map(requirement_name);
        merge_package(&mut edges, name, deps);
    }
    Ok(LockfileGraph { edges })
}

/// Distribution name at the head of a PEP 508 string such as
/// `urllib3<3,>=1.21.1` or `requests[socks]==2.31.0; python_version >= "3.8"`.
fn requirement_name(spec: &str) -> Option<String> {
    let name = spec
        .trim_start()
        .split(|ch: char| !(ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_' | '.')))
        .next()
        .unwrap_or_default();
    (!name.is_empty()).then(|| normalize_distribution_name(name))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(contents: &str) -> Result<LockfileGraph, ManifestError> {
        let temp = tempfile::tempdir().expect("tempdir");
        let path = temp.path().join("pdm.lock");
        std::fs::write(&path, contents).expect("write pdm.lock");
        extract_pdm_lock(&path)
    }

    const PDM_2_LOCK: &str = r#"
# This file is @generated by PDM.
# It is not intended for manual editing.

[metadata]
groups = ["default", "dev"]
strategy = ["inherit_metadata"]
lock_version = "4.5.0"
content_hash = "sha256:abc"

[[metadata.targets]]
requires_python = ">=3.11"

[[package]]
name = "requests"
version = "2.32.3"
requires_python = ">=3.8"
summary = "Python HTTP for Humans."
groups = ["default"]
dependencies = [
    "certifi>=2017.4.17",
    "charset-normalizer<4,>=2",
    "idna<4,>=2.5",
    "urllib3<3,>=1.21.1",
]
files = [
    {file = "requests-2.32.3-py3-none-any.whl", hash = "sha256:70761cfe"},
]

[[package]]
name = "requests"
version = "2.32.3"
extras = ["socks"]
requires_python = ">=3.8"
groups = ["default"]
dependencies = [
    "PySocks!=1.5.7,>=1.5.6",
    "requests==2.32.3",
]

[[package]]
name = "urllib3"
version = "2.2.3"
requires_python = ">=3.8"
groups = ["default"]

[[package]]
name = "pytest"
version = "8.3.3"
groups = ["dev"]
dependencies = [
    "colorama; sys_platform == \"win32\"",
    "iniconfig",
]
"#;

    #[test]
    fn extracts_pdm_2_lock() {
        let graph = parse(PDM_2_LOCK).expect("valid pdm.lock");
        assert_eq!(
            graph.edges.get("requests"),
            Some(&vec![
                "certifi".to_owned(),
                "charset-normalizer".to_owned(),
                "idna".to_owned(),
                "urllib3".to_owned(),
                "pysocks".to_owned(),
                "requests".to_owned(),
            ])
        );
        assert_eq!(
            graph.edges.get("pytest"),
            Some(&vec!["colorama".to_owned(), "iniconfig".to_owned()])
        );
        assert_eq!(graph.edges.get("urllib3"), Some(&Vec::new()));
    }

    #[test]
    fn requirement_name_stops_at_first_non_name_character() {
        assert_eq!(requirement_name("urllib3<3"), Some("urllib3".to_owned()));
        assert_eq!(
            requirement_name(" Foo_Bar[x]==1; os_name == 'nt'"),
            Some("foo-bar".to_owned())
        );
        assert_eq!(requirement_name("idna"), Some("idna".to_owned()));
        assert_eq!(requirement_name(">=1"), None);
        assert_eq!(requirement_name(""), None);
    }

    #[test]
    fn rejects_invalid_toml() {
        let error = parse("[[package\n").expect_err("invalid TOML");
        assert!(matches!(error, ManifestError::InvalidLockfile { .. }));
    }

    mod props {
        use super::*;
        use proptest::prelude::*;

        proptest! {
            #[test]
            fn extract_pdm_lock_never_panics(contents in "\\PC{0,400}") {
                let _ = parse(&contents);
            }

            #[test]
            fn requirement_name_never_panics(spec in "\\PC{0,60}") {
                if let Some(name) = requirement_name(&spec) {
                    prop_assert_eq!(normalize_distribution_name(&name), name);
                }
            }
        }
    }
}
