//! `poetry.lock` graph extraction.

use std::collections::BTreeMap;
use std::path::Path;

use toml::Value;

use super::error::ManifestError;
use super::lockfile::{array_tables, merge_package, read_lock_table};
use super::pep508_util::normalize_distribution_name;
use super::types::LockfileGraph;

/// Parse `poetry.lock` (lock-version 1.x and 2.x) into a dependency name graph.
///
/// `[package.dependencies]` keys are the dependency names whatever the value
/// shape (version string, table, or array of marker-split tables), and
/// `[metadata.files]` from 1.x is ignored.
pub fn extract_poetry_lock(path: &Path) -> Result<LockfileGraph, ManifestError> {
    let table = read_lock_table(path)?;
    let mut edges = BTreeMap::new();
    for package in array_tables(&table, "package") {
        let Some(name) = package.get("name").and_then(Value::as_str) else {
            continue;
        };
        let deps = package
            .get("dependencies")
            .and_then(Value::as_table)
            .into_iter()
            .flat_map(toml::Table::keys)
            .map(String::as_str)
            .map(normalize_distribution_name);
        merge_package(&mut edges, name, deps);
    }
    Ok(LockfileGraph { edges })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(contents: &str) -> Result<LockfileGraph, ManifestError> {
        let temp = tempfile::tempdir().expect("tempdir");
        let path = temp.path().join("poetry.lock");
        std::fs::write(&path, contents).expect("write poetry.lock");
        extract_poetry_lock(&path)
    }

    const LOCK_V1_1: &str = r#"
[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
category = "main"
optional = false
python-versions = ">=3.7"

[package.dependencies]
certifi = ">=2017.4.17"
charset-normalizer = ">=2,<4"
urllib3 = ">=1.21.1,<3"

[package.extras]
socks = ["PySocks (>=1.5.6,!=1.5.7)"]

[[package]]
name = "urllib3"
version = "2.0.4"
description = "HTTP library"
category = "main"
optional = false
python-versions = ">=3.7"

[metadata]
lock-version = "1.1"
python-versions = "^3.11"
content-hash = "abc"

[metadata.files]
requests = [
    {file = "requests-2.31.0-py3-none-any.whl", hash = "sha256:58cd"},
]
urllib3 = []
"#;

    const LOCK_V2_0: &str = r#"
# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.

[[package]]
name = "Flask"
version = "3.0.3"
description = "A simple framework for building complex web applications."
optional = false
python-versions = ">=3.8"
files = [
    {file = "flask-3.0.3-py3-none-any.whl", hash = "sha256:34e8"},
]

[package.dependencies]
blinker = ">=1.6.2"
colorama = {version = "*", markers = "platform_system == \"Windows\""}
importlib-metadata = [
    {version = ">=3.6.0", markers = "python_version < \"3.10\""},
]
Werkzeug = ">=3.0.0"

[[package]]
name = "werkzeug"
version = "3.0.4"
description = "The comprehensive WSGI web application library."
optional = false
python-versions = ">=3.8"
files = []

[metadata]
lock-version = "2.0"
python-versions = "^3.11"
content-hash = "def"
"#;

    /// Dependency order follows the TOML map, which may or may not preserve
    /// insertion order depending on crate features.
    fn sorted_deps(graph: &LockfileGraph, name: &str) -> Vec<String> {
        let mut deps = graph.edges.get(name).cloned().expect("package present");
        deps.sort();
        deps
    }

    #[test]
    fn extracts_lock_version_1_1() {
        let graph = parse(LOCK_V1_1).expect("valid poetry.lock 1.1");
        assert_eq!(
            sorted_deps(&graph, "requests"),
            vec!["certifi", "charset-normalizer", "urllib3"]
        );
        assert!(sorted_deps(&graph, "urllib3").is_empty());
        assert_eq!(graph.edges.len(), 2);
    }

    #[test]
    fn extracts_lock_version_2_0() {
        let graph = parse(LOCK_V2_0).expect("valid poetry.lock 2.0");
        assert_eq!(
            sorted_deps(&graph, "flask"),
            vec!["blinker", "colorama", "importlib-metadata", "werkzeug"]
        );
        assert!(sorted_deps(&graph, "werkzeug").is_empty());
    }

    #[test]
    fn rejects_invalid_toml() {
        let error = parse("[[package\n").expect_err("invalid TOML");
        assert!(matches!(error, ManifestError::InvalidLockfile { .. }));
    }

    mod props {
        use super::*;
        use proptest::prelude::*;

        proptest! {
            #[test]
            fn extract_poetry_lock_never_panics(contents in "\\PC{0,400}") {
                let _ = parse(&contents);
            }

            #[test]
            fn extract_poetry_lock_never_panics_on_package_shapes(
                name in "\\PC{0,20}",
                dep in "[A-Za-z0-9._-]{1,20}",
            ) {
                let contents = format!(
                    "[[package]]\nname = {name:?}\n\n[package.dependencies]\n{dep:?} = [1, {{version = \"*\"}}]\n"
                );
                let _ = parse(&contents);
            }
        }
    }
}
