#!/usr/bin/env python3
"""Generate bundled package-module and binary maps for chokkin resolver."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SEED = ROOT / "data" / "package-map.seed.json"
BINARY_SEED = ROOT / "data" / "binary-map.seed.json"
OUT_PKG = ROOT / "src" / "resolver" / "bundled" / "package_modules.rs"
OUT_BIN = ROOT / "src" / "resolver" / "bundled" / "binaries.rs"

# Common packages where distribution name normalizes to the import root.
AUTO_PACKAGES = [
    "aiohttp",
    "anyio",
    "attrs",
    "babel",
    "black",
    "boto3",
    "botocore",
    "cachetools",
    "certifi",
    "cffi",
    "charset-normalizer",
    "click",
    "colorama",
    "coverage",
    "cryptography",
    "django",
    "dnspython",
    "docutils",
    "fastapi",
    "filelock",
    "flake8",
    "flask",
    "frozenlist",
    "fsspec",
    "greenlet",
    "grpcio",
    "h11",
    "httpcore",
    "httpx",
    "hypothesis",
    "idna",
    "iniconfig",
    "isort",
    "itsdangerous",
    "jinja2",
    "jmespath",
    "jsonschema",
    "lxml",
    "markdown",
    "markupsafe",
    "matplotlib",
    "more-itertools",
    "multidict",
    "mypy",
    "numpy",
    "oauthlib",
    "openpyxl",
    "orjson",
    "packaging",
    "pandas",
    "paramiko",
    "pathspec",
    "platformdirs",
    "pluggy",
    "protobuf",
    "psutil",
    "psycopg2-binary",
    "pyarrow",
    "pycparser",
    "pydantic",
    "pygments",
    "pyjwt",
    "pymongo",
    "pyparsing",
    "pytest",
    "pytest-cov",
    "python-dateutil",
    "pytz",
    "pyyaml",
    "redis",
    "referencing",
    "regex",
    "requests",
    "rich",
    "rpds-py",
    "rsa",
    "ruff",
    "s3transfer",
    "setuptools",
    "six",
    "sniffio",
    "soupsieve",
    "sqlalchemy",
    "sqlparse",
    "starlette",
    "structlog",
    "tomli",
    "tqdm",
    "typer",
    "typing-extensions",
    "tzdata",
    "urllib3",
    "uvicorn",
    "virtualenv",
    "watchdog",
    "werkzeug",
    "wheel",
    "wrapt",
    "yarl",
    "zipp",
]


def normalize(name: str) -> str:
    parts: list[str] = []
    pending = False
    for ch in name.lower():
        if ch in "-_.":
            pending = True
            continue
        if pending and parts:
            parts.append("-")
            pending = False
        parts.append(ch)
    if pending and parts:
        parts.append("-")
    return "".join(parts)


def import_root(dist: str) -> str:
    return normalize(dist).replace("-", "_")


def load_packages() -> dict[str, list[str]]:
    data = json.loads(SEED.read_text(encoding="utf-8"))
    packages: dict[str, list[str]] = {}
    for entry in data.get("packages", []):
        dist = normalize(entry["distribution"])
        imports = sorted({str(item) for item in entry["imports"]})
        packages[dist] = imports

    auto_names = list(AUTO_PACKAGES)
    auto_names.extend(data.get("auto_packages", []))
    for dist in auto_names:
        norm = normalize(dist)
        if norm not in packages:
            root = import_root(norm)
            packages[norm] = [root]

    return dict(sorted(packages.items()))


def render_packages(packages: dict[str, list[str]]) -> str:
    lines = [
        "// @generated by scripts/generate-package-map.py — do not edit",
        "#![allow(clippy::doc_markdown)]",
        "",
        "/// Bundled distribution to import names (PyPI top packages + curated mismatches).",
        f"pub static PACKAGE_TO_IMPORTS: &[(&str, &[&str])] = &[",
    ]
    for dist, imports in packages.items():
        import_list = ", ".join(f'"{name}"' for name in imports)
        lines.append(f'    ("{dist}", &[{import_list}]),')
    lines.append("];")
    lines.append("")
    lines.append(f"pub const PACKAGE_MAP_ENTRY_COUNT: usize = {len(packages)};")
    lines.append("")
    return "\n".join(lines)


def render_binaries(entries: list[dict[str, str]]) -> str:
    lines = [
        "// @generated by scripts/generate-package-map.py — do not edit",
        "#![allow(clippy::doc_markdown)]",
        "",
        "/// Bundled CLI binary name to distribution name.",
        "pub static BINARY_TO_DISTRIBUTION: &[(&str, &str)] = &[",
    ]
    for entry in sorted(entries, key=lambda item: item["binary"]):
        lines.append(f'    ("{entry["binary"]}", "{normalize(entry["distribution"])}"),')
    lines.append("];")
    lines.append("")
    lines.append(f"pub const BINARY_MAP_ENTRY_COUNT: usize = {len(entries)};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    packages = load_packages()
    if len(packages) < 200:
        raise SystemExit(f"expected >= 200 package map entries, got {len(packages)}")

    OUT_PKG.parent.mkdir(parents=True, exist_ok=True)
    OUT_PKG.write_text(render_packages(packages), encoding="utf-8")

    binary_data = json.loads(BINARY_SEED.read_text(encoding="utf-8"))
    OUT_BIN.write_text(render_binaries(binary_data["binaries"]), encoding="utf-8")
    print(f"wrote {len(packages)} package entries -> {OUT_PKG}")
    print(f"wrote {len(binary_data['binaries'])} binary entries -> {OUT_BIN}")


if __name__ == "__main__":
    main()
