[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "build-setuptools-scm"
dynamic = ["version"]
dependencies = ["setuptools-scm", "click"]

[tool.setuptools_scm]

[tool.setuptools.packages.find]
where = ["src"]
include = ["acme*"]
exclude = ["acme.tests*"]
